### ISSUE TITLE
When using new themes feature with black background, cannot read Details because it uses black font on black background

### ISSUE THREAD

**Issue by ddecristo** [keesschollaart81/vsts-sprint-goal#161] opened 2020-09-28 19:51 UTC
It appeared that the Details was noteditable because I changed the theme to be black instead of white background using the new preview feature. However the real issue is that it is using black font on black background unlike the sprint goal which uses white on black thus it only looked like it wasn't editable but it was.

**Comment by jerone** [comment] 2020-12-30 13:24
Duplicate of #39

**Comment by jerone** [comment] 2021-01-21 17:09
@keesschollaart81 Would be great if you could fix this (again).

🇳🇱 We zouden deze extentie graag vollop willen gebruiken.

**Comment by keesschollaart81** [comment] 2021-02-23 16:07
Fixed with #44, now released to prod

**Closed by keesschollaart81** 2021-02-23 16:07 UTC
